package com.service.comm.controller;

public class ResponseMsg
{
    public static final String
            GET_MALL_INFO_SUCC                              = "获取交易大厅信息成功",
            GET_MALL_INFO_ERR                               = "获取交易大厅信息失败",
            GET_MALL_INFO_RELATION_ID_ERROR                 = "获取交易大厅信息失败，交易对不存在",
            ADD_ORDER_SUCC                                  = "委托下单成功",
            ADD_ORDER_ERR                                   = "委托下单失败",
            UNDO_ORDER_SUCC                                 = "撤销委托下单成功",
            UNDO_ORDER_ERR                                  = "撤销委托下单失败",
            UPDATE_BALANCE_SUCC                             = "更新余额成功",
            UPDATE_BALANCE_ERR                              = "更新余额失败",
            LIST_CURRENT_ORDER_SUCC                         = "获取当前委托列表成功",
            LIST_CURRENT_ORDER_ERR                          = "获取当前委托列表失败",
            LIST_HISTORY_ORDER_SUCC                         = "获取历史委托列表成功",
            LIST_HISTORY_ORDER_ERR                          = "获取历史委托列表失败",
            LIST_MARKET_SUCC                                = "获取市场涨幅列表信息成功",
            LIST_MARKET_ERR                                 = "获取市场涨幅列表信息失败",
            PAGE_MARKET_SUCC                                  ="获取首页市场列表成功",
            PAGE_MARKET_ERR                                    ="获取首页市场列表失败",
            LIST_SELL_ORDER_SUCC                            = "获取卖单列表成功",
            LIST_SELL_ORDER_ERR                             = "获取卖单列表失败",
            LIST_BUY_ORDER_SUCC                             = "获取买单列表成功",
            LIST_BUY_ORDER_ERR                              = "获取买单列表失败",
            LIST_REAL_TIME_ORDER_SUCC                       = "获取实时交易列表成功",
            LIST_REAL_TIME_ORDER_ERR                        = "获取实时交易列表失败",
            MY_FUND_SUCC                                    = "获取我的资产成功",
            MY_FUND_ERR                                     = "获取我的资产失败",
            ADD_FAV_SUCC                                    = "添加自选成功",
            ADD_FAV_ERR                                     = "添加自选失败",
            MY_FAV_SUCC                                     = "我的自选成功",
            MY_FAV_ERR                                      = "我的自选失败",
            PAGE_MY_FAV_SUCC                                ="首页我的自选成功",
            PAGE_MY_FAV_ERR                                 ="首页我的自选失败",
            LIST_UP_DOWN_SUCC                              ="获取涨跌幅成功",
            LIST_UP_DOWN_ERR                               ="获取涨跌幅失败",
            LIST_CURRENCY_SUCC                              = "获取市場信息table成功",
            LIST_CURRENCY_ERR                               = "获取市場信息table失敗",
            NEW_TRANSACTION_PRICE_SUCC                      = "获取最新成交价成功",
            NEW_TRANSACTION_PRICE_ERR                       = "获取最新成交价失败",
            LIST_NEW_TRANSACTION_PRICE_SUCC                 = "获取最新成交价成功",
            LIST_NEW_TRANSACTION_PRICE_ERR                  = "获取最新成交价失败",
            SCROLL_MARKET_INFO_SUCC                         = "获取滚动市场信息成功" ,
            CROLL_MARKET_INFO_ERR                           = "获取滚动市场信息失败",
            DETAIL_TRADE_SUCC                               = "获取交易详情成功",
            DETAIL_TRADE_ERR                                = "获取交易详情失败",
            LIST_TRADE_CURRENCY_SUCC                        = "获取主货币信息成功",
            LIST_TRADE_CURRENCY_ERR                         = "获取主货币信息失败",
            LIST_TRADE_DETAILS_CONDITION_SUCC               = "获取成交明细成功" ,
            LIST_TRADE_DETAILS_CONDITION_ERR                = "获取成交明细失败",
            LIST_PAY_CURRENCY_SUCC                          = "获取支付币信息列表成功",
            LIST_PAY_CURRENCY_ERR                           = "获取支付币信息列表失败",
            PARAM_ERR                                       = "请输入正确的参数",
            ADD_ORDER_PARAM_EMPTY_ERR                       = "下单参数不能为空",
            TOKEN_EMPTY_ERR                                 = "token不能为空或不存在",
            TOKEN_ERR                                       = "token凭证已过期或错误",
            UNDO_ORDER_PARAM_EMPTY_ERR                      = "撤单参数不能为空",
            BALANCE_ERR                                     = "余额不足",
            GET_COMMISSION_DISCOUNT_SUCC                    = "获取返佣记录成功",
            GET_COMMISSION_DISCOUNT_ERROR_TOKEN_INVALID     = "获取返佣记录失败，token不合法",
            GET_COMMISSION_DISCOUNT_BILLBOARD_SUCC          = "获取返佣榜单成功",
            GET_CURRENCY_TO_USDT_EXCHANGE_SUCC              = "获取货币对USDT汇率成功",
            GET_DEFAULT_RELATION_ID_SUCC                              ="获取默认交易对id成功",
            GET_DEFAULT_RELATION_ID_ERR                   ="获取默认交易对id失败",
            CURRENCY_CONVERSION_SUCC                        = "法币换算成功",
            CURRENCY_CONVERSION_ERR                         = "法币换算错误",
            NEW_PRICE_CURRENCY_CONVERSION_SUCC              = "最新价法币换算成功",
            NEW_PRICE_CURRENCY_CONVERSION_ERR               = "最新价法币换算错误",
            CURRECY_RELATION_DETAIL_SUCC                    ="获取交易对信息成功",
            CURRECY_RELATION_DETAIL_ERR                     ="获取交易对信息失败",
            WITHDRAW_DEPOSIT_SUCC                              ="充提币成功",
            WITHDRAW_DEPOSIT_ERR                             ="充提币失败",
            SEND_COIN_ERR                                       ="赠币失败",
            SEND_COIN_SUCC                                      = "赠币成功",
            USER_TRADE_ERR                                           = "用户限制交易",
            RELATION_ERR                                         = "交易对错误",
            CURRENCY_TRADE_ERR                                    = "货币限制交易",
            MARKET_AMOUNT_ERR                                     = "市价买入卖出量过低";


}
