package com.service.comm.model.dbo;

import lombok.Data;

import java.util.Date;

@Data
public class DcAddressETHDO
{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_address_eth.id
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_address_eth.uid
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_address_eth.address
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_address_eth.is_used
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    private Byte isUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_address_eth.path
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_address_eth.enter_code
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    private String enterCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_address_eth.keystore
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    private String keystore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_address_eth.private_key
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    private String privateKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_address_eth.create_time
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_address_eth.update_time
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_address_eth.id
     *
     * @return the value of dc_address_eth.id
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_address_eth.id
     *
     * @param id the value for dc_address_eth.id
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_address_eth.uid
     *
     * @return the value of dc_address_eth.uid
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_address_eth.uid
     *
     * @param uid the value for dc_address_eth.uid
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_address_eth.address
     *
     * @return the value of dc_address_eth.address
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_address_eth.address
     *
     * @param address the value for dc_address_eth.address
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_address_eth.is_used
     *
     * @return the value of dc_address_eth.is_used
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public Byte getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_address_eth.is_used
     *
     * @param isUsed the value for dc_address_eth.is_used
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public void setIsUsed(Byte isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_address_eth.path
     *
     * @return the value of dc_address_eth.path
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_address_eth.path
     *
     * @param path the value for dc_address_eth.path
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_address_eth.enter_code
     *
     * @return the value of dc_address_eth.enter_code
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public String getEnterCode() {
        return enterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_address_eth.enter_code
     *
     * @param enterCode the value for dc_address_eth.enter_code
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public void setEnterCode(String enterCode) {
        this.enterCode = enterCode == null ? null : enterCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_address_eth.keystore
     *
     * @return the value of dc_address_eth.keystore
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public String getKeystore() {
        return keystore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_address_eth.keystore
     *
     * @param keystore the value for dc_address_eth.keystore
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public void setKeystore(String keystore) {
        this.keystore = keystore == null ? null : keystore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_address_eth.private_key
     *
     * @return the value of dc_address_eth.private_key
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_address_eth.private_key
     *
     * @param privateKey the value for dc_address_eth.private_key
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey == null ? null : privateKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_address_eth.create_time
     *
     * @return the value of dc_address_eth.create_time
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_address_eth.create_time
     *
     * @param createTime the value for dc_address_eth.create_time
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_address_eth.update_time
     *
     * @return the value of dc_address_eth.update_time
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_address_eth.update_time
     *
     * @param updateTime the value for dc_address_eth.update_time
     *
     * @mbg.generated Wed Aug 01 11:23:52 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}
